name: Test App CI

on:
  push:
    branches: [ "main", "setup-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: ''

    - name: Build and Test with Maven
      run: mvn clean install
