name: Test App CI

on:
  push:
    branches: [ "main", "features", "bugfixes" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'microsoft'

    - name: Build and Test with Maven
      run: mvn clean install
