name: Test App CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: user_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          -p 5440:5432
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build and Test with Maven
        run: |
          SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5440/user_db \
          SPRING_DATASOURCE_USERNAME=user \
          SPRING_DATASOURCE_PASSWORD=password \
          mvn clean install

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: dockerforomar/test-app
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


